version: "3.9"

services:
  backend:
    build: ./backend
    container_name: nurse-backend
    ports:
      - "5000:3000"
    env_file:
      - ./backend/.env
    networks:
      - nurse-net

  frontend:
    build: ./frontend
    container_name: nurse-frontend
    ports:
      - "3000:80"
    env_file:
      - ./backend/.env
    depends_on:
      - backend
    networks:
      - nurse-net

networks:
  nurse-net:
    driver: bridge
